# Future instruction
When it comes to updating database objects at the start of the season, I need to ensure each df fits with its corresponding db table.
In terms of "fit":
    <br>&emsp;If replace, ensure the new object contains all data and none is lost
    <br>&emsp;If append, ensure the df to be unioned is correct

In [30]:
import pandas as pd; pd.set_option('display.max_columns', 500)
from sqlalchemy.dialects.postgresql.base import PGDialect; PGDialect._get_server_version_info = lambda *args: (9, 2)
from dataHub import dataHub
dh = dataHub()

db_con = dh.db_connect('cockroach')
postgre = dh.db_connect('postgre')
fty_con = dh.fty_api_con()

# Player Season Stats
Updated at the start of the season and can continue to be updated daily or weekly. This depends on how frequently the season_stat object is refreshed on the nba_api

In [11]:
player_season_stats = dh.get_player_season_stats(db_con)
# player_season_stats.head()

--------------------- player season stats
player: 0 / 535
player: 50 / 535
player: 100 / 535
player: 150 / 535
player: 200 / 535
player: 250 / 535
player: 300 / 535
player: 350 / 535
player: 400 / 535
player: 450 / 535
player: 500 / 535
player: 534 / 535
player_season_stats has been updated

In [14]:
player_season_stats['season_id'].max()

'2022-23'

# Player Info
Updated once at the start of each season

In [15]:
player_info = dh.get_player_info(db_con)
# player_info.head()

--------------------- player_info
player: 0 / 535
player: 50 / 535
player: 100 / 535
player: 150 / 535
player: 200 / 535
player: 250 / 535
player: 300 / 535
player: 350 / 535
player: 400 / 535
player: 450 / 535
player: 500 / 535
player: 534 / 535
player_info has been updated

In [19]:
player_info['from_year'].min()

2003

# Player Game Log
Updated at the start of the season and daily for the rest of the season. Remember to control for season type list ['Pre Season', 'Regular Season', etc....]

In [21]:
pd.read_sql_query('SELECT MAX(game_date) FROM nba.player_game_log', db_con)

          max
0  2023-06-12

In [22]:
player_game_log = dh.get_player_game_log(db_con)
# player_game_log.head()

--------------------- player_game_log
player: 0 / 535
player: 50 / 535
player: 100 / 535
player: 150 / 535
player: 200 / 535
player: 250 / 535
player: 300 / 535
player: 350 / 535
player: 400 / 535
player: 450 / 535
player: 500 / 535
player: 534 / 535
player_game_log has been updated to: 2023-10-05

/Users/fred/git/nba_cockroach_db/dataHub.py:144: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['GAME_DATE'] = to_datetime(df['GAME_DATE'])

In [30]:
player_game_log.head(
    
)

,year_season,slug_season,season_type,game_date,game_id,matchup,wl,player_id,fgm,fga,fg_pct,fg3_m,fg3_a,fg3_pct,ft_pct,video_available,min,ftm,fta,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,plus_minus
0,2023,2023-24,Pre Season,2023-10-05,0012300001,MIN vs. DAL,W,1629638,3,5,0.600,3,5,0.6,1.0,2,22,2,2,0,5,5,5,0,2,1,1,11,4
1,2023,2023-24,Pre Season,2023-10-05,0012300001,MIN vs. DAL,W,203937,1,4,0.250,0,1,0.0,0.0,2,19,0,2,0,1,1,5,1,1,2,3,2,-3
2,2023,2023-24,Pre Season,2023-10-05,0012300001,DAL @ MIN,L,1630535,0,3,0.000,0,0,0.0,0.0,2,12,0,0,0,4,4,0,0,2,1,5,0,-11
3,2023,2023-24,Pre Season,2023-10-05,0012300001,MIN vs. DAL,W,1628972,2,6,0.333,2,5,0.4,0.0,2,18,0,0,0,7,7,1,0,0,0,3,6,7
4,2023,2023-24,Pre Season,2023-10-05,0012300001,MIN vs. DAL,W,201144,2,3,0.667,1,2,0.5,0.0,2,17,0,0,0,2,2,4,3,0,2,0,5,22

# Game Schedule
Use update_historical_game_schedule() to update records from last season. Use get_next_game_schedule() to obtain schedule for upcoming season. Run both functions at the start of each season

In [ ]:
hist_game_schedule = dh.update_historical_game_schedule(db_con)
hist_game_schedule.head()

In [ ]:
next_game_schedule = dh.get_next_game_schedule(db_con)
next_game_schedule.head()

# Team Roster
Updated at the start of the season and after trade deadline

In [ ]:
team_roster = dh.get_team_roster(db_con)
team_roster.head()

# Fantasy data instruction
Do this part later

# Free Agents
Updated daily

In [ ]:
free_agents = dh.fty_get_free_agents(fty_con.free_agents(size=1000), db_con)
free_agents.head()

# Fantasy Team Rosters
Updated daily

In [ ]:
fty_con.teams