In [1]:
import configparser
from os import getcwd
from pytz import timezone
import pandas as pd
from yfpy.query import YahooFantasySportsQuery
from nba_api.stats.library.parameters import Season
from sqlalchemy.sql import text
from datetime import datetime, date, timedelta
from sqlalchemy.dialects.postgresql.base import PGDialect; PGDialect._get_server_version_info = lambda *args: (9, 2)
from dataHub import dataHub
dh = dataHub()

db_con = dh.db_connect('postgre')
fty_con = dh.fty_con(db_con)

# fty_con = fty_con['Yahoo;121793']

In [2]:
dh.fty_get_league_competitor(fty_con, db_con)

2024-10-17 20:13:25.126 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.

league_competitor has been updated

,season,platform,league_id,competitor_id,competitor_abbrev,competitor_name,division_id,division_name
0,2024-25,ESPN,95537,1,SUSA,Suva Street Sandwhichs,0,A team
1,2024-25,ESPN,95537,2,CASH,Palmy Slizzards,0,A team
2,2024-25,ESPN,95537,3,Nix,Nixon Administration,0,A team
3,2024-25,ESPN,95537,5,JOEL,Trust The Process,0,A team
4,2024-25,ESPN,95537,9,SIMO,Hooked on a Bealing,0,A team
5,2024-25,ESPN,95537,11,42°,Exact Angles,0,A team
6,2024-25,ESPN,95537,17,Piki,DJ Haraz,0,A team
7,2024-25,ESPN,95537,21,SBRN,Acoustic and Regarded,0,A team
8,2024-25,ESPN,95537,22,DD3,DB Deep 3s,0,A team
9,2024-25,ESPN,95537,24,YOZA,WHAKVTAN3 W3STSID3RS,0,A team
10,2024-25,ESPN,95537,25,FRED,s4aggy_camel,0,A team
11,2024-25,ESPN,95537,26,Days,Daisies,0,A team
0,2024-25,Yahoo,121793,1,Fleet,Philly 5 ⭐️ Men,None,None
1,2024-25,Yahoo,121793,2,Oli,shaggy_camel,None,None
2,2024-25,Yahoo,121793,3,Cameron,Cameron's Choice Team,None,None
3,2024-25,Yahoo,121793,4,Step2Cool,draftbyslo,None,None
4,2024-25,Yahoo,121793,5,Jeremy,Palmy Slizzards,None,None
5,2024-25,Yahoo,121793,6,Jeremy,Jeremy's Incredible Team,None,None
6,2024-25,Yahoo,121793,7,jason,The Yucatan Bandits,None,None
7,2024-25,Yahoo,121793,8,Jess,Taranaki Thunder,None,None

In [3]:
dh.fty_get_league_schedule(fty_con, db_con)

2024-10-17 20:13:27.109 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:28.597 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:30.802 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:33.068 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:35.310 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:37.450 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:39.613 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:41.833 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:44.122 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.

league_schedule has been updated

,season,platform,league_id,week,week_start,week_end,competitor_id,opponent_id
0,2024-25,ESPN,95537,1,2024-10-21,2024-10-27,1,9
1,2024-25,ESPN,95537,2,2024-10-28,2024-11-03,1,21
2,2024-25,ESPN,95537,3,2024-11-04,2024-11-10,1,22
3,2024-25,ESPN,95537,4,2024-11-11,2024-11-17,1,26
4,2024-25,ESPN,95537,5,2024-11-18,2024-11-24,1,3
...,...,...,...,...,...,...,...,...
147,2024-25,Yahoo,121793,15,2025-02-03,2025-02-09,8,7
148,2024-25,Yahoo,121793,16,2025-02-10,2025-02-23,8,2
149,2024-25,Yahoo,121793,17,2025-02-24,2025-03-02,8,5
150,2024-25,Yahoo,121793,18,2025-03-03,2025-03-09,8,3
151,2024-25,Yahoo,121793,19,2025-03-10,2025-03-16,8,4

In [4]:
dh.fty_get_competitor_roster(fty_con, db_con)

2024-10-17 20:13:46.308 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:47.882 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:49.538 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:51.839 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:54.075 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:56.321 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:13:58.612 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:00.966 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:03.318 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:05.619 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:07.906 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:10.125 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:12.396 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:14.635 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:16.882 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:19.201 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:21.485 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:23.736 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:26.000 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:28.274 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:29.865 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:32.151 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:34.375 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:36.679 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:39.080 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:41.422 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:43.746 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:45.992 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:48.362 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:50.668 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:52.949 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:55.219 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:57.565 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:14:59.955 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:02.243 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:03.960 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:06.285 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:08.661 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:10.958 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:13.231 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:15.485 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:17.733 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:19.984 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:22.211 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:24.503 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:26.870 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:29.225 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:31.451 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:33.667 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:35.931 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:37.490 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:39.745 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:41.998 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:44.218 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:46.515 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:48.721 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:50.963 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:53.215 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:55.488 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:15:57.799 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:00.084 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:02.313 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:04.598 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:06.829 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:09.042 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:10.637 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:14.872 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:17.098 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:19.341 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:21.598 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:23.832 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:26.092 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:28.367 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:30.614 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:32.826 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:35.066 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:37.273 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:39.481 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:41.756 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:43.965 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:46.185 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:48.460 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:50.023 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:52.262 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:54.479 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:56.686 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:16:58.914 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:01.203 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:03.427 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:05.649 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:07.902 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:10.193 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:12.448 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:14.650 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:16.895 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:19.141 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:21.361 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:22.923 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:25.165 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:27.393 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:29.667 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:31.905 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:34.152 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:36.391 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:38.605 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:40.837 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:43.100 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:45.331 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:47.570 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:49.792 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:52.065 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:54.302 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:55.877 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:17:58.084 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:00.294 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:02.542 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:04.782 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:07.012 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:09.243 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:11.500 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:13.740 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:16.006 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:18.239 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:20.486 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:22.729 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:24.986 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.

competitor_roster has been updated

,season,platform,league_id,timestamp,league_week,competitor_id,player_fantasy_id,player_name,player_team,player_injury_status,player_acquisition_type
0,2024-25,ESPN,95537,2024-10-17 20:13:46.304856+13:00,1,1,4432573,Paolo Banchero,ORL,ACTIVE,DRAFT
1,2024-25,ESPN,95537,2024-10-17 20:13:46.304883+13:00,1,1,3112335,Nikola Jokic,DEN,DAY_TO_DAY,DRAFT
2,2024-25,ESPN,95537,2024-10-17 20:13:46.304887+13:00,1,1,3908809,Donovan Mitchell,CLE,ACTIVE,DRAFT
3,2024-25,ESPN,95537,2024-10-17 20:13:46.304890+13:00,1,1,4278067,Nic Claxton,BKN,DAY_TO_DAY,DRAFT
4,2024-25,ESPN,95537,2024-10-17 20:13:46.304893+13:00,1,1,4433287,Brandon Miller,CHA,ACTIVE,DRAFT
...,...,...,...,...,...,...,...,...,...,...,...
112,2024-25,Yahoo,121793,2024-10-17 20:18:16.006142+13:00,1,8,6035,Anfernee Simons,POR,GTD,None
113,2024-25,Yahoo,121793,2024-10-17 20:18:18.239585+13:00,1,8,5840,Kyle Kuzma,WAS,,None
114,2024-25,Yahoo,121793,2024-10-17 20:18:20.486167+13:00,1,8,5663,Ivica Zubac,LAC,,None
115,2024-25,Yahoo,121793,2024-10-17 20:18:22.728983+13:00,1,8,5600,Ben Simmons,BKN,GTD,None
116,2024-25,Yahoo,121793,2024-10-17 20:18:24.986214+13:00,1,8,10100,Keyonte George,UTA,,None

In [ ]:
dh.fty_get_free_agents(fty_con, db_con)

2024-10-17 20:18:28.839 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:30.422 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:32.021 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:33.633 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:35.236 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:36.826 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:38.412 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:40.017 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:41.613 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:43.198 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:44.791 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:46.401 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:47.987 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:49.584 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:51.172 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:52.783 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:54.366 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:55.979 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:57.591 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:18:59.200 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:00.819 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:02.424 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:04.034 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:05.644 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:07.243 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:08.833 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:10.415 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:11.946 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:13.346 - ERROR - query.py - yfpy.query:543 - No data found when attempting extraction from fields: ['league', 'players']
2024-10-17 20:19:13.348 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:14.761 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:16.168 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:17.569 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:18.973 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:20.418 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:21.827 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:23.243 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:24.644 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:26.062 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:27.453 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:28.856 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:30.271 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:31.702 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:33.101 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:34.511 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:35.932 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:37.369 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:38.807 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:40.217 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:42.666 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:44.052 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:45.456 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:46.868 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:48.267 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:49.674 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:51.105 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:52.527 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:53.934 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:55.341 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:56.762 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:58.161 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:19:59.564 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:01.008 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:02.441 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:03.867 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:05.270 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:06.668 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:08.095 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:09.491 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:10.900 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:12.325 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:13.737 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:15.201 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:16.654 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:18.083 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:19.639 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:21.174 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:22.694 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:24.123 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:25.559 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:27.011 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:28.528 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:29.965 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:31.413 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:32.934 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:34.364 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:35.805 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:37.350 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:38.875 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:40.310 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:41.849 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:43.374 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:44.784 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:46.366 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:47.890 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:49.418 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:50.971 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:52.491 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:53.938 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:55.457 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:56.891 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:58.336 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:20:59.762 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:01.292 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:02.728 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:04.179 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:05.701 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:07.238 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:08.666 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:10.203 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:11.655 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:13.188 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:14.611 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:16.045 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:17.479 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:18.915 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:20.448 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:21.896 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:23.319 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:24.749 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:26.196 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:27.722 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:29.156 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:30.706 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:32.224 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:33.657 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:35.090 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:36.527 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:38.046 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:39.475 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:40.932 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:42.364 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:43.799 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:45.239 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:46.774 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:48.319 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:49.836 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:51.375 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:52.822 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:54.460 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:55.984 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:57.431 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.
2024-10-17 20:21:58.953 - WARNING - query.py - yfpy.query:1030 - No game id or season/year provided, defaulting to current fantasy season.

In [ ]:
dh.fty_get_recent_activity(fty_con, db_con)

In [ ]:
# for team in [team.team_id for team in query.get_league_teams()]:
#     query.get_team_stats_by_week(team)